#165894987 Build out the user signup endpoint
danose/Quick-Credit pull request #70
Opened 2019-05-17 11:09 UTC by danose

#### What does this PR do?
Have user signup endpoint for the Quick credit app

#### Description of Task to be completed?
Have the endpoint below working:
POST /api/v1/loans

#### How should this be manually tested?
- Using Post with localhost of 5000, test the endpoint

#### What are relevant pivotal tracker stories?
#165894987

2019-05-17 11:24 UTC, V-84 requested changes
Attend to the comments

2019-05-17 11:24 UTC, JohnMadakin commented on api/v1/controllers/usersController.js
> +        .header('x-auth-access', token)
Remove this.. you don't need to put this in the header

2019-05-17 11:24 UTC, JohnMadakin commented on api/v1/controllers/usersController.js
> +            firstName: user.first_name,
Remove the user information and store them in the token instead

2019-05-18 00:02 UTC, V-84 reviewed
attend to the comment

2019-05-18 00:02 UTC, V-84 commented on api/v1/controllers/usersController.js
> +          token
add `message: 'Success'`

2019-05-18 00:02 UTC, JohnMadakin commented on api/v1/controllers/usersController.js
> +          error: 'user with that EMAIL or phone number already exists'
replace `error` with `message`

2019-05-18 00:02 UTC, JohnMadakin commented on api/v1/controllers/usersController.js
> +          error: 'user with that EMAIL or phone number already exists'
status code should be 409

2019-05-18 00:02 UTC, JohnMadakin commented on api/v1/controllers/usersController.js
> +     * @param {string} req
req is an object

2019-05-18 00:02 UTC, JohnMadakin commented on api/v1/controllers/usersController.js
> +     * @param {Array} res
res is an object

2019-05-18 06:34 UTC, danose commented on api/v1/controllers/usersController.js
> +          error: 'user with that EMAIL or phone number already exists'
Noted

2019-05-18 06:34 UTC, danose commented on api/v1/controllers/usersController.js
> +     * @param {string} req
noted

2019-05-18 09:56 UTC, merged